### ISSUE TITLE
Change description on GitHub project repo landing page

### ISSUE THREAD

**Issue by cvan** [aframevr/awesome-aframe#102]
This is the current description on the [repo's landing page](https://github.com/aframevr/awesome-aframe):

`A collection of awesome things regarding the A-Frame ecosystem.`

@ngokevin: what do you think of changing the description to the following?

`A collection of awesome resources for the A-Frame WebVR framework.`

Or perhaps this one?

`A list of awesome resources for the A-Frame WebVR framework.`

**Comment by cvan** [comment]
If we decide to change the project description, we should also update the description in the [`README.md` file](https://github.com/aframevr/awesome-aframe/blob/1c477b6/README.md#awesome-aframe-).

**Comment by cvan** [comment]
Could we also add [`https://aframe.io/`](https://aframe.io/) as the Project URL?

**Comment by ngokevin** [comment]
done
