### ISSUE TITLE
aframe with Ionic 2 framework

### ISSUE THREAD

**Issue by amity203** [aframevr/awesome-aframe#106]
Do you know of any example, which can provide setup as how to use aframe within ionic 2 mobile app

**Comment by ngokevin** [comment]
Ionic is primarily a UI library, no? You probably want to use what it's built on, Cordova, instead. (Or Crosswalk)

**Comment by amity203** [comment]
ionic is much more than UI library, it already useing crosswalk, as its a framework. i am able to figure out when and how to include iframe, i did try import and require, but getting error, trying to find solutions lets see if someone can help here

**Comment by ngokevin** [comment]
I've used Ionic before, but you don't need what Ionic provides on top of Crosswalk. We can just use Crosswalk, itself right? What Ionic brings is the Angular, styles, themes, animations etc., to make stuff look native, which isn't needed in a 3D/WebGL context.

**Comment by amity203** [comment]
I wanted to make VR and 3D part in one of my ionic mobile app, that is why i am using ionic, otherwise i was able to use aframe in simple html file as well. You have compiled a very extensive list of resources so i was wondering if i can find something which used ionic 2 as well.

**Comment by ngokevin** [comment]
I see. Try sticking an `<a-scene embedded>` in your Ionic app and see what happens. Should just work.

**Comment by amity203** [comment]
i changed that also, but main problem is i am not able to figure out way to use aframe.js, when i did require, it is like client side things dont work with required, when i used : import 'aframe', i got error: Uncaught TypeError: Cannot assign to read only property 'detachedCallback' of object '#<a-node>' , this is the only way when i see aframe under node module in sources in chrome dev tools.
I did import * as af from 'aframe', no error, but nothing aframe was not dowloaded under node module, seems like only ref import 'aframe' works but than it give below error:
Uncaught TypeError: Cannot assign to read only property 'detachedCallback' of object '#<a-node>'
this is generated in pollyfill.js which gets created at build time

**Comment by ngokevin** [comment]
Can you just add as a script tag in your HTML?

**Comment by amity203** [comment]
trust me i tried whole day yesterday including script tag, but this time it worked with script tag.
At least aframe code started running.
Thank a lot
