### ISSUE TITLE
Link to 24 Ways Article

### ISSUE THREAD

**Issue by ShaneHudson** [aframevr/awesome-aframe#116]
I have written an article for 24 Ways titled First Steps in VR. It's meant as a way to encourage web designers and developers to get involved in VR, using A-Frame as it has a low learning curve.

Article: https://24ways.org/2016/first-steps-in-vr/
Code: https://github.com/ShaneHudson/First-Steps-In-VR
Live Demo: https://shanehudson.net/tools/first-steps-in-vr/02-maze-map/index.html

**Comment by cvan** [comment]
really awesome article. I like how you ease in the reader to the advanced concepts and show the entire end-to-end workflow 👍
