### ISSUE TITLE
how to learn this ?

### ISSUE THREAD

**Issue by oahzuw** [aframevr/awesome-aframe#127]
I would like to make a map like this, there are tutorials?

http://vrviewer.istaging.co/#!/684173

**Comment by shaunmnemonic** [comment]
Hi @oahzuw 

There are some tutorials here -- https://github.com/aframevr/awesome-aframe#tutorials and others on the main Aframe site starting here -- https://aframe.io/docs/0.5.0/guides/building-a-basic-scene.html

They should be enough to get you started, but if not, join the Aframe community on Slack - https://aframevr-slack.herokuapp.com/ - and ask in the #questions channel.

**Comment by oahzuw** [comment]
@shaunmnemonic   Thanks for the answer, these tutorials I will go to read, also joined the Slack, thanks aframevr development so strong library, thanks again for your answer, sorry my english is not good!

**Comment by ngokevin** [comment]
We've discontinued awesome. Thanks!
