### ISSUE TITLE
Angular CLI support

### ISSUE THREAD

**Issue by aammfe** [aframevr/awesome-aframe#138]
Hi!

I m genuinely Astonished to see how easy ,Powerful and optimal  A-Frame is. 
i m guy from unity,  i love to work in strong type languages but as A-frame is build in js, 
it would rather difficult for me and others like me, to take full advantage of it.

Is there any plan for angular support ?
I know there are other A-frame Angular projects available. but because of leak of knowledge i did not make it work.    
I m looking for simple solutions like A-frame hello word.

I would be truly help if u can provide Support for Angular too.
Kind Regards.

**Comment by shaunmnemonic** [comment]
Hi @aammfe - this particular repo isn't for the core Aframe framework and is actually just a place to show some additional resources, tools and projects that use Aframe. 

Aframe itself should be useable with Angular, you may want to jump onto Slack -- https://aframevr-slack.herokuapp.com/ and try the #questions channel and ask there if anyone has worked with Angular. This Post (http://blog.brakmic.com/webvr-with-a-frame-angular/) may also help.

**Comment by ngokevin** [comment]
We've discontinued awesome. Thanks!
