### ISSUE TITLE
Add Kevin's ForwardJS talk

### ISSUE THREAD

**Issue by cvan** [aframevr/awesome-aframe#43]
Perhaps should wait until video is published, but the slides are available now:

http://www.slideshare.net/MozVR/build-the-virtual-reality-web-with-aframe/
https://github.com/ngokevin/forwardjs-presentation/

**Comment by ngokevin** [comment]
Yeah, have to wait till the video is published, and unfortunately I will have to do a re-recording of the screen and some video compositing work to overlay it.
