### ISSUE TITLE
Link to some/all of Humane Virtuality posts

### ISSUE THREAD

**Issue by cvan** [aframevr/awesome-aframe#93]
Great series by @armthethinker: https://medium.com/humane-virtuality

**Comment by cvan** [comment]
Also relevant: http://andrewrmchugh.rocks/projects/humane-virtuality.php

**Comment by ngokevin** [comment]
it's been featured frequently on the AWOA, I've been keeping up. I have some volunteers to sync the awesome aframe from AWOA

**Comment by ngokevin** [comment]
We've discontinued awesome. Thanks!
