### ISSUE TITLE
Sync missing entries from A Week of A-Frame to awesome-aframe

### ISSUE THREAD

**Issue by ngokevin** [aframevr/awesome-aframe#95]

**Comment by SteveX** [comment]
It would be useful (to me, just a suggestion) to have a "Latest Additions" section showing new links from the past month.

I do visit A Week of A-Frame each week with enthusiasm, but the amount of time I can spend on it is variable depending on the week. Looking through the commits for awesome-aframe is something I do too, but it takes a while, so it would be helpful to see a list of recent additions.

**Comment by ngokevin** [comment]
We've discontinued awesome. Thanks!
